/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BrowserController.h"
#import "MobileSafari-Structs.h"
#import "RotatablePopoverControllerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "BrowserPanel.h"
#import "BrowserToolbarDelegate.h"
#import "BookmarksNavigationControllerDelegate.h"
#import "RecentlyClosedTabViewControllerDelegate.h"
#import "TabBarDelegate.h"
#import "UIWebPDFViewHandlerDelegate.h"
#import "MFMailComposeViewControllerDelegate.h"
#import "MCProfileConnectionObserver.h"
#import "BackForwardTableViewControllerDelegate.h"
#import "FindOnPageToolbarDelegate.h"
#import "UIActionSheetDelegate.h"
#import <WebUI/WebUIDelegate.h>

@class TabDocument, UIWindow, BrowserRootViewController, RecentlyClosedTabViewController, QuickLookBannerController, NSTimer, UIScrollView, NSString, BrowserToolbar, NSMutableArray, AddressView, UIWebBrowserView, NSURL, UIView, TabSnapshotContext, ConsoleView, RotatablePopoverController, UITransitionView, UITapGestureRecognizer, BannerView, UIFrameAnimation, WebUIAuthenticationManager, NSRecursiveLock, BrowserReaderView, WebFrame, TabController;

@interface BrowserController : WebUIDelegate <BrowserPanel, MFMailComposeViewControllerDelegate, UIActionSheetDelegate, UIScrollViewDelegate, BackForwardTableViewControllerDelegate, MCProfileConnectionObserver, FindOnPageToolbarDelegate, UIWebPDFViewHandlerDelegate> {
	UIWindow *_window;
	TabController *_tabController;
	BrowserToolbar *_buttonBar;
	int _pushedRunLoops;
	BrowserRootViewController *_rootViewController;
	AddressView *_addressView;
	UIView *_backgroundColorView;
	UIScrollView *_scrollView;
	UIWebBrowserView *_browserView;
	UITransitionView *_transitionView;
	UIView *_pageView;
	id _lockedBookmarksDatabaseAlert;
	ConsoleView *_consoleView;
	QuickLookBannerController *_quickLookBannerController;
	UITapGestureRecognizer *_quickLookTapRecognizer;
	BannerView *_bannerView;
	BOOL _bannerViewIsAnimating;
	BOOL _debuggingEnabled;
	UIView *_titleAndLockContainerView;
	SEL _scrollToTopDidEndSelector;
	BOOL _tabBarItemsFixed;
	id<BrowserPanel> _browserPanel;
	id<BrowserPanel> _nextBrowserPanel;
	RotatablePopoverController *_currentPopoverController;
	BOOL _isShowingCurrentPanel;
	NSURL *_mailToURL;
	NSMutableArray *_documentsPendingClose;
	CGRect _nextPanelPresentationRectInToolbar;
	BOOL _isRotating;
	int _orientation;
	int _previousOrientation;
	BOOL _isZooming;
	BOOL _isProgressEnabled;
	float _progress;
	BOOL _resourcesLoading;
	BOOL _showingProgressIndicator;
	TabDocument *_documentWhoseProgressIsShown;
	NSTimer *_hideAddressViewTimer;
	NSTimer *_idleTimerDurationTimer;
	double _idleTimerDuration;
	int _currentlyLoadingResourcesCount;
	unsigned _coalescedUpdateMask;
	BOOL _isRunningTabExposeTest;
	unsigned _tabExposeTestLoadCount;
	unsigned _tabExposeTestIterationsRemaining;
	NSString *_currentLocaleIdentifier;
	BOOL _geolocationDialogAllowed;
	BOOL _antiPhishingServiceInitialized;
	BOOL _processingIsSuspended;
	NSTimer *_resumeUpdatesTimer;
	int _notifyLockStateToken;
	unsigned long long _phoneIsLocked;
	BOOL _isPrivateBrowsingEnabled;
	UIFrameAnimation *_addressViewSlideAnimation;
	WebUIAuthenticationManager *_authenticationManager;
	TabSnapshotContext *_asynchronousTabSnapshotContext;
	NSRecursiveLock *_asynchronousTabSnapshotContextLock;
	WebFrame *_frameToBePrinted;
	int _currentFindOnPageResultNumber;
	BOOL _zoomToHighlightSelection;
	BOOL _leaveKeyboardUpOnPanelReveal;
	CGRect _inputViewScreenBoundsAfterRotation;
	float _lastAdjustmentForKeyboard;
	CFDateFormatterRef _dateFormatter;
	BrowserReaderView *_readerView;
	BOOL _readerViewIsStale;
	BOOL _readerShouldBeShownIfPossible;
	RecentlyClosedTabViewController *_recentlyClosedTabController;
}
@property(readonly, retain) AddressView *addressView;
@property(readonly, retain) TabSnapshotContext *asynchronousTabSnapshotContext;
@property(readonly, retain) NSRecursiveLock *asynchronousTabSnapshotContextLock;
@property(readonly, retain) BannerView *bannerView;
@property(readonly, retain) UIWebBrowserView *browserView;
@property(readonly, retain) BrowserToolbar *buttonBar;
@property(retain, nonatomic) RotatablePopoverController *currentPopoverController;
@property(readonly, assign) CFDateFormatterRef dateFormatter;
@property(retain, nonatomic) NSURL *mailToURL;
@property(readonly, assign) int orientation;
@property(assign, nonatomic) BOOL readerShouldBeShownIfPossible;
@property(readonly, retain) BrowserReaderView *readerView;
@property(assign, nonatomic) BOOL readerViewIsStale;
@property(readonly, retain) TabController *tabController;
@property(readonly, retain) UIWindow *window;
+ (id)contentBackgroundColor;
+ (void)releaseSharedBrowserController;
+ (id)sharedBrowserController;
- (CGRect)_addressViewFrame;
- (CGRect)_addressViewFrameScrollViewCoords;
- (void)_bannerAnimationDidStop:(id)_bannerAnimation finished:(id)finished;
- (void)_bannerAnimationDidStopAndShouldRemove:(id)_bannerAnimation finished:(id)finished;
- (id)_currentPDFSearchResult;
- (void)_didFinishTakingSnapshotOnWebThread;
- (BOOL)_hasRemoteInspectorProfileInstalled;
- (void)_highlightFindOnPageMatch:(BOOL)match;
- (void)_highlightFindOnPageMatchForPDF:(BOOL)pdf withPDFHandler:(id)pdfhandler;
- (void)_highlightNextMatch;
- (void)_highlightPreviousMatch;
- (BOOL)_highlightSelection;
- (void)_initSubviews;
- (float)_pdfPageNumberLabelYOffset;
- (CGRect)_quickLookFrame;
- (void)_resetIdleTimer;
- (void)_restoreStateFromSnapshotContext:(id)snapshotContext;
- (void)_setFrameToBePrinted:(id)bePrinted;
- (void)_setIdleTimerDuration:(double)duration;
- (void)_setPrivateBrowsingEnabled:(BOOL)enabled;
- (BOOL)_showingAModalAlertWillHang;
- (void)_takeSnapshotOnWebThread;
- (id)_topScrollView;
- (void)_updateCurrentResultLabel;
- (BOOL)_updateCurrentSearchIndex:(BOOL)index;
- (void)_updateEVOrganizationName;
- (void)_updateRemoteInspectorAfterPreferenceChange;
- (BOOL)addReadingListBookmarkForCurrentTabUpdatingController:(id)currentTabUpdatingController;
- (void)addRecentSearch:(id)search;
- (void)backForwardTableViewController:(id)controller didSelectWebHistoryItem:(id)item;
- (CGRect)bannerViewFrame;
- (id)browserPanel;
- (id)bundleVersion;
- (float)buttonBarHeightForBarSize:(int)barSize;
- (float)buttonBarHeightForOrientation:(int)orientation;
- (int)buttonBarSize;
- (int)buttonBarSizeForOrientation:(int)orientation;
- (void)cancelFromAuthenticationManager:(id)authenticationManager forChallenge:(id)challenge;
- (void)carrierBundledChanged;
- (void)clearAutoFillMessageReceived;
- (void)clearHistoryMessageReceived;
- (void)clearRecentSearches;
- (void)clearUserHistory;
- (id)containerViewForAuthenticationPanel;
- (int)currentResultIndex;
- (void)dealloc;
- (CGRect)defaultWebLayerFrame;
- (CGRect)defaultWebLayerFrameWithDebugConsoleEnabled:(BOOL)debugConsoleEnabled;
- (void)didCompleteGestures;
- (void)didCompleteGesturesOrScrolling;
- (void)didCompleteScrolling;
- (void)didReadDefaults;
- (void)document:(id)document changedView:(id)view;
- (void)done;
- (CGRect)frameForAddressViewEditing;
- (CGRect)frameForDisplayingAddressView:(id)displayingAddressView;
- (CGRect)frameForPDFViewWithHandler:(id)handler proposedFrame:(CGRect)frame;
- (CGRect)frameForReaderView;
- (void)goBack;
- (void)goForward;
- (void)goToAddress:(id)address fromAddressView:(id)addressView;
- (id)handleExternalURL:(id)url;
- (BOOL)hasMatches;
- (void)hideBanner:(id)banner removeView:(BOOL)view;
- (void)hideReaderForTabDocument:(id)tabDocument animated:(BOOL)animated deactivationMode:(int)mode;
- (void)highlightSearchResultBounds:(CGRect)bounds resultRects:(id)rects contentViews:(id)views forPDFViewHandler:(id)pdfviewHandler;
- (id)iconSizedSnapshotForTabDocument:(id)tabDocument;
- (BOOL)ignoresPrivateBrowsingStyle;
- (BOOL)isAnyPageLoaded;
- (BOOL)isAtEndOfPage;
- (BOOL)isShowingReader;
- (id)keyboardSuperview;
- (void)loadURL:(id)url;
- (void)localeChanged:(CFLocaleRef)changed;
- (void)logInFromAuthenticationManager:(id)authenticationManager withCredential:(id)credential forChallenge:(id)challenge;
- (void)next;
- (CGPoint)originForPDFPageLabelViewWithHandler:(id)handler proposedOrigin:(CGPoint)origin;
- (int)panelState;
- (int)panelType;
- (int)pausesPages;
- (void)pdfViewHandler:(id)handler linkClicked:(id)clicked;
- (void)prepareToTakeSnapshotOfReaderInTabDocument:(id)tabDocument context:(id)context;
- (void)prepareToTakeSnapshotOfTabDocument:(id)tabDocument context:(id)context;
- (void)previous;
- (BOOL)privateBrowsingEnabled;
- (id)productVersion;
- (void)profileConnectionDidReceiveProfileListChangedNotification:(id)profileConnection userInfo:(id)info;
- (id)recentSearches;
- (id)recentSearchesMatchingPrefix:(id)prefix;
- (void)removeQuickLookBannerView;
- (void)restoreStateFromHistoryItem:(id)historyItem forWebView:(id)webView;
- (void)resume;
- (void)saveRecentSearches:(id)searches;
- (void)saveStateToHistoryItem:(id)historyItem forWebView:(id)webView;
- (void)scrollDown;
- (void)scrollToTopWithDidEndSelector:(SEL)scrollToTopWith;
- (CGSize)scrollViewContentSize;
- (CGSize)scrollViewContentSizeForPDF;
- (void)scrollViewDidEndDecelerating:(id)scrollView;
- (void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidScroll:(id)scrollView;
- (void)scrollViewDidScrollToTop:(id)scrollView;
- (CGRect)scrollViewFrameForBrowserSize:(CGSize)browserSize;
- (BOOL)scrollViewShouldScrollToTop:(id)scrollView;
- (void)scrollViewWasRemoved:(id)removed;
- (void)scrollViewWillBeginDragging:(id)scrollView;
- (void)setBackgroundColor:(id)color;
- (void)setButtonBarAlwaysInFront:(BOOL)front;
- (void)setCookiePolicyMessageReceived;
- (void)setDocumentView:(id)view;
- (void)setInitialZoomScaleForPPT:(float)ppt;
- (void)setLeaveKeyboardUpOnPanelReveal:(BOOL)reveal;
- (void)setProgressEnabled:(BOOL)enabled;
- (void)setRemoteInspectorEnabled:(BOOL)enabled;
- (void)setShowingReader:(BOOL)reader animated:(BOOL)animated;
- (void)setUsesStatusBarStyleBlackOpaque:(BOOL)opaque duration:(float)duration;
- (void)setupWithURL:(id)url;
- (BOOL)shouldHideOnSuspend;
- (void)showBanner:(id)banner;
- (void)showPrintingDuringLoadAlert;
- (void)showQuickLookBannerView;
- (void)showReaderForTabDocument:(id)tabDocument animated:(BOOL)animated;
- (id)snapshotForTabDocument:(id)tabDocument;
- (id)snapshotForTabDocument:(id)tabDocument withSize:(CGSize)size;
- (id)snapshotForTabDocument:(id)tabDocument withSize:(CGSize)size maintainAspectRatio:(BOOL)ratio;
- (void)suspendForEventsOnly:(BOOL)eventsOnly;
- (void)tabDocumentSecureContentStatusHasChanged:(id)changed;
- (id)textForCurrentResultLabel;
- (id)textForToolbarLabel;
- (void)toggleAlwaysShowBookmarksBarMessageReceived;
- (id)topBrowserView;
- (void)updateAddress:(BOOL)address forTabDocument:(id)tabDocument;
- (void)updateAddressViewFrame;
- (void)updateBackgroundColorForTabDocument:(id)tabDocument;
- (void)updateBackgroundViewFrame;
- (void)updateBannerViewFrame;
- (void)updateBanners:(BOOL)banners forTabDocument:(id)tabDocument;
- (void)updateButtonBarFrame;
- (void)updateButtonBarFrameForOrientation:(int)orientation;
- (void)updateButtons;
- (BOOL)updateHighlightBubbleWobble:(BOOL)wobble;
- (void)updateIdleTimerDuration;
- (void)updateInterface:(BOOL)interface;
- (void)updatePanelsForTabDocument:(id)tabDocument;
- (void)updateProgress:(BOOL)progress forTabDocument:(id)tabDocument;
- (void)updateScrollIndicatorTopInset;
- (void)updateScrollViewContentSize;
- (void)updateScrollViewFrame;
- (void)updateSearchText:(id)text;
- (void)updateTitle:(BOOL)title forTabDocument:(id)tabDocument;
- (void)updateViewsAfterStatusBarChange;
- (void)updateWebViewSizeAttributes;
- (id)userAgentForURL:(id)url;
- (void)userEmptiedCachesMessageReceived;
- (void)view:(id)view didDrawInRect:(CGRect)rect duration:(double)duration;
- (void)view:(id)view didSetFrame:(CGRect)frame oldFrame:(CGRect)frame3 asResultOfZoom:(BOOL)zoom;
- (void)webThreadWebViewDidLayout:(id)webThreadWebView;
- (void)webView:(id)view decidePolicyForGeolocationRequestFromOrigin:(id)origin frame:(id)frame listener:(id)listener;
- (void)webView:(id)view didDrawRect:(CGRect)rect;
- (void)webView:(id)view printFrameView:(id)view2;
- (void)webView:(id)view runJavaScriptAlertPanelWithMessage:(id)message initiatedByFrame:(id)frame;
- (BOOL)webView:(id)view runJavaScriptConfirmPanelWithMessage:(id)message initiatedByFrame:(id)frame;
- (id)webView:(id)view runJavaScriptTextInputPanelWithPrompt:(id)prompt defaultText:(id)text initiatedByFrame:(id)frame;
- (void)webView:(id)view willAssistFormNode:(id)node;
- (void)webView:(id)view willClickElement:(id)element;
- (void)webViewDidClick:(id)webView;
- (void)webViewDidDrawTiles:(id)webView;
- (void)webViewDidNotClick:(id)webView;
- (void)webViewMainFrameDidCommitLoad:(id)webViewMainFrame;
- (void)webViewMainFrameDidFinishLoad:(id)webViewMainFrame;
- (void)webViewMainFrameDidFirstVisuallyNonEmptyLayoutInFrame:(id)webViewMainFrame;
- (BOOL)webViewRotateShouldCenterSelectionRect:(id)webViewRotate;
- (BOOL)webViewShouldInterruptJavaScript:(id)webView;
- (void)willSuspend;
@end

@interface BrowserController (BrowserControllerUI)
- (void)_hideAddressView;
- (void)_inputViewWillRotate:(id)_inputView;
- (void)_keyboardDidShow:(id)_keyboard;
- (void)_keyboardWillHide:(id)_keyboard;
- (void)_keyboardWillShow:(id)_keyboard;
- (void)_performCoalescedUpdate:(BOOL)update type:(int)type;
- (void)_setHideAddressViewTimer:(id)timer;
- (void)_slideInAddressView:(BOOL)addressView;
- (void)_updateProgressIndicator;
- (void)addressViewWillHideProgress:(id)addressView withDelay:(double)delay;
- (void)addressViewWillShowProgress:(id)addressView;
- (void)animationDidStop:(id)animation finished:(id)finished context:(void *)context;
- (void)animator:(id)animator startAnimation:(id)animation;
- (void)animator:(id)animator stopAnimation:(id)animation fraction:(float)fraction;
- (void)performCoalescedUpdates;
- (void)setEllipsedTextViewNeedsUpdate:(BOOL)update;
- (void)setProgress:(float)progress forceUpdate:(BOOL)update;
- (void)setProgressViewNeedsUpdate:(BOOL)update;
- (void)setReloadImageViewNeedsUpdate:(BOOL)update;
- (void)setResourcesLoading:(BOOL)loading;
- (void)setTitleTextViewNeedsUpdate:(BOOL)update;
- (void)updateAddressViewSearchEngineStrings;
@end

@interface BrowserController (DeveloperBannerViewDelegate)
- (BOOL)shouldEnableDeveloperBannerView:(id)view;
@end

@interface BrowserController (DeveloperBannerViewDataSource)
- (id)messageForDeveloperBannerView:(id)developerBannerView;
@end

@interface BrowserController (ConsoleDataSource)
- (id)messageAtIndex:(int)index matchingMask:(int)mask;
- (int)numberOfMessagesMatchingMask:(int)messagesMatchingMask;
@end

@interface BrowserController (ConsoleDelegate)
- (id)activeWebView;
- (void)clearMessagesMatchingMask:(int)mask;
@end

@interface BrowserController (UITransitionViewDelegate)
- (void)transitionViewDidComplete:(id)transitionView fromView:(id)view toView:(id)view3;
- (void)transitionViewDidStart:(id)transitionView;
@end

@interface BrowserController (Developer)
@property(assign) BOOL debuggingEnabled;
- (void)_transferViewToTitleTextContainerView:(id)titleTextContainerView;
- (void)_transferViewToTransitionView:(id)transitionView;
- (id)consoleView;
- (void)consoleViewDidEndSession:(id)consoleView;
- (void)hideConsoleView;
- (void)refreshConsoleMessages;
- (void)scrollAndTransitionToConsoleView;
- (void)tabDocumentDidClearMessages:(id)tabDocument;
- (void)tabDocumentDidReceiveMessage:(id)tabDocument;
- (void)transitionToConsoleView;
@end

@interface BrowserController (BrowserControllerGestures)
@property(assign) CGPoint contentOffset;
@property(assign) float zoomScale;
- (void)_gesturesEnded;
- (BOOL)_isShowingFullScreenPlugInUI;
- (float)_maxZoomScale;
- (float)_minZoomScale;
- (id)_pdfView;
- (CGRect)browserFrameForOrientation:(int)orientation;
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
- (void)getRotationContentSettings:(XXStruct_3uUjXA *)settings;
- (BOOL)isRotating;
- (BOOL)isZooming;
- (id)rotatingFooterView;
- (id)rotatingHeaderView;
- (CGSize)scrollView:(id)view contentSizeForZoomScale:(float)zoomScale withProposedSize:(CGSize)proposedSize;
- (void)scrollViewDidEndZooming:(id)scrollView withView:(id)view atScale:(float)scale;
- (void)scrollViewDidZoom:(id)scrollView;
- (CGRect)scrollViewFrameForOrientation:(int)orientation;
- (void)scrollViewWillBeginZooming:(id)scrollView withView:(id)view;
- (id)viewForZoomingInScrollView:(id)scrollView;
- (CGSize)webView:(id)view contentSizeForScrollView:(id)scrollView;
- (CGRect)webViewFrameForOrientation:(int)orientation;
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
- (void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
- (id)zoomAndTabTestURL;
@end

@interface BrowserController (BrowserControllerPanels) <BookmarksNavigationControllerDelegate, BrowserToolbarDelegate>
@property(retain) id browserPanel;
- (id)_actionsForElement:(id)element withTargetURL:(id)targetURL suggestedActions:(id)actions;
- (id)_addToReadingListActionForElement:(id)element withTargetURL:(id)targetURL;
- (void)_animateNode:(id)node intoButton:(int)button afterLinkImageDisappears:(id)disappears;
- (void)_animateTabDocument:(id)document intoBackgroundFromLinkNode:(id)linkNode;
- (void)_delayedShowLockedBookmarksDatabaseAlertForBookmarkAddition;
- (void)_doSearch:(id)search;
- (void)_forceDismissModalViewController;
- (void)_forceDismissModalViewController:(BOOL)controller;
- (void)_handleAddBookmarkSelector:(SEL)selector;
- (id)_hostForFindOnPagePanel;
- (id)_openInNewPageActionForElement:(id)element withTargetURL:(id)targetURL;
- (id)_panelForPanelType:(int)panelType;
- (id)_panelSuperview;
- (void)_presentModalViewController:(id)controller fromRectInToolbar:(CGRect)toolbar;
- (void)_setEnteringURL:(BOOL)url;
- (void)_setNextBrowserPanel:(id)panel;
- (void)_setPrivateBrowsingStyleForNextPanel:(id)nextPanel;
- (void)_setShowingActionPanel:(BOOL)panel animate:(BOOL)animate;
- (void)_setShowingAddBookmark:(BOOL)bookmark;
- (void)_setShowingAlert:(BOOL)alert;
- (void)_setShowingBookmarks:(BOOL)bookmarks animate:(BOOL)animate;
- (void)_setShowingButtonBar:(BOOL)bar;
- (void)_setShowingCurrentPanel:(BOOL)panel;
- (void)_setShowingCurrentPanel:(BOOL)panel animate:(BOOL)animate;
- (void)_setShowingFindOnPagePanel:(BOOL)panel;
- (void)_setShowingMailComposePanel:(BOOL)panel;
- (void)_setShowingPrintPanel:(BOOL)panel;
- (void)_setShowingTweetController:(BOOL)controller;
- (void)_setShowingWebClipPanel:(BOOL)panel;
- (void)_setUserInteractionEnabled:(BOOL)enabled;
- (BOOL)_shouldShowButtonBarForPanel:(id)panel;
- (BOOL)_togglePanelType:(int)type;
- (void)_transitionToBrowserPanel:(id)browserPanel;
- (void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
- (void)actionSheet:(id)sheet didDismissWithButtonIndex:(int)buttonIndex;
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;
- (void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
- (void)animateScrollToAddressField;
- (void)backFromButtonBar;
- (void)beginEnteringURL;
- (void)browserPanel:(id)panel didChangeState:(int)state;
- (void)closeBrowserPanel:(id)panel;
- (void)composeEmailWithMailToURL:(id)url;
- (BOOL)createAndAddToHomeScreenBundleForWebClip:(id)webClip;
- (void)didHideBrowserPanel:(id)panel;
- (void)didPresentActionSheet:(id)sheet;
- (void)didPresentAlertView:(id)view;
- (void)didShowBrowserPanel:(id)panel;
- (void)dismissCurrentPopover;
- (void)dismissCurrentPopover:(BOOL)popover;
- (void)doSearch:(id)search fromAddressView:(id)addressView;
- (void)forwardFromButtonBar;
- (void)goToBookmark:(id)bookmark;
- (void)goToHistoryURL:(id)historyURL;
- (BOOL)hideBrowserPanel;
- (BOOL)hideBrowserPanelType:(int)type;
- (void)mailComposeController:(id)controller didFinishWithResult:(int)result error:(id)error;
- (void)popupAlert:(id)alert;
- (void)presentAlertSheet:(id)sheet;
- (void)presentBackForwardController:(id)controller fromRect:(CGRect)rect;
- (void)presentBackPopoverFromButtonBar;
- (void)presentForwardPopoverFromButtonBar;
- (void)reloadFromAddressView:(id)addressView;
- (void)resignWebViewFirstResponder;
- (void)shareURLOrArticle;
- (void)sheetController:(id)controller performAction:(int)action forAlert:(id)alert;
- (void)sheetControllerDidHideSheet:(id)sheetController;
- (void)sheetControllerDidShowSheet:(id)sheetController;
- (void)showActionPanelFromButtonBar;
- (void)showAddBookmarkSheet;
- (void)showAddToHomeScreenSheet;
- (BOOL)showBrowserPanelType:(int)type;
- (void)showLockedBookmarksDatabaseAlertForBookmarkAdditionAfterDelay;
- (void)showLockedBookmarksDatabaseAlertInView:(id)view forBookmarkAddition:(BOOL)bookmarkAddition;
- (void)showTweetController;
- (void)stopFromAddressView:(id)addressView;
- (id)superviewForImageSheetForWebView:(id)webView;
- (void)toggleBookmarksFromButtonBar;
- (void)toggleTabsFromButtonBar;
- (void)webClip:(id)clip iconRequestDidFinishWithImage:(id)iconRequest precomposed:(BOOL)precomposed;
- (void)webClip:(id)clip startupImageRequestDidFinishWithImage:(id)startupImageRequest;
- (void)webClip:(id)clip startupLandscapeImageRequestDidFinishWithImage:(id)startupLandscapeImageRequest;
- (id)webView:(id)view actionsForImageElement:(id)imageElement withTargetURL:(id)targetURL suggestedActions:(id)actions;
- (id)webView:(id)view actionsForLinkElement:(id)linkElement withTargetURL:(id)targetURL suggestedActions:(id)actions;
- (void)willHideBrowserPanel:(id)panel;
- (void)willShowBrowserPanel:(id)panel;
@end

@interface BrowserController (BrowserControllerTabs) <TabBarDelegate, RecentlyClosedTabViewControllerDelegate, RotatablePopoverControllerDelegate>
- (void)_addAuthenticationChallenge:(id)challenge displayNow:(BOOL)now;
- (id)_blankTabDocumentToReuse;
- (void)_closeDocument:(id)document;
- (void)_makeRoomForNewTabDocument:(id)newTabDocument;
- (void)_runTabExposeTest;
- (void)_setTabBarItemsFixed:(BOOL)fixed;
- (id)_tabDocumentRepresentedByTabBarItem:(id)item;
- (void)_updateTabExposeButtonIndicatorExcludingBlanks:(BOOL)blanks;
- (BOOL)closePendingDocuments;
- (CGRect)defaultScreenShotFrame;
- (void)didStartLoadingResource;
- (void)didStopLoadingResource;
- (void)finishedTabExposeTest;
- (CGRect)frameWhenReturningFromExpose;
- (void)hideBannerForTabExpose;
- (BOOL)isBannerHiddenForTabExpose;
- (BOOL)isRunningTabExposeTest;
- (id)loadURLInNewWindow:(id)newWindow inBackground:(BOOL)background;
- (id)loadURLInNewWindow:(id)newWindow inBackground:(BOOL)background animated:(BOOL)animated;
- (id)loadURLInNewWindow:(id)newWindow inBackground:(BOOL)background animated:(BOOL)animated fromExternalApplication:(BOOL)externalApplication;
- (void)popoverController:(id)controller willPresentAfterRotationToInterfaceOrientation:(int)interfaceOrientation;
- (void)popoverControllerDidDismissPopover:(id)popoverController;
- (BOOL)prepareTabExposeTest;
- (void)recentlyClosedTabViewController:(id)controller didSelectTabDocument:(id)document;
- (void)resetViewOnTabDocument:(id)document;
- (void)runTabExposeTest;
- (void)setShowingTabs:(BOOL)tabs;
- (void)showBannerFromTabExpose;
- (CGRect)snapshotFrameForCurrentScrollViewContentOffset;
- (void)switchFromTabDocument:(id)tabDocument toTabDocument:(id)tabDocument2 inBackground:(BOOL)background;
- (void)tabBar:(id)bar activateItem:(id)item;
- (BOOL)tabBar:(id)bar canCloseItem:(id)item;
- (BOOL)tabBar:(id)bar canMoveItem:(id)item;
- (void)tabBar:(id)bar closeItem:(id)item;
- (void)tabBar:(id)bar moveItem:(id)item overItem:(id)item3;
- (void)tabBarAddTab:(id)tab;
- (void)tabBarAddTabLongPress:(id)press;
- (BOOL)tabBarCanAddTab:(id)tab;
- (void)tabController:(id)controller composeEmailWithMailToURL:(id)url forTabDocument:(id)tabDocument;
- (void)tabController:(id)controller didFinishLoadingWithError:(BOOL)error;
- (void)tabController:(id)controller didSwitchFromTabDocument:(id)tabDocument toTabDocument:(id)tabDocument3 inBackground:(BOOL)background;
- (void)tabController:(id)controller hideAlertForTabDocument:(id)tabDocument;
- (void)tabController:(id)controller showAlertForTabDocument:(id)tabDocument;
- (void)tabController:(id)controller tabDocument:(id)document didCancelAuthenticationChallenge:(id)challenge;
- (void)tabController:(id)controller tabDocument:(id)document didReceiveAuthenticationChallenge:(id)challenge fromDataSource:(id)dataSource;
- (void)tabController:(id)controller tabDocumentDidUpdateBackForward:(id)tabDocument;
- (void)tabController:(id)controller tabDocumentDidUpdateTitle:(id)tabDocument;
- (void)tabController:(id)controller tabDocumentDidUpdateURL:(id)tabDocument;
- (void)tabControllerDidStartLoading:(id)tabController;
- (CGRect)tabControllerFrame;
- (void)tabDocument:(id)document progressChanged:(float)changed;
- (void)tabDocumentProgressDidStall:(id)tabDocumentProgress;
- (void)updateTabBarAnimated:(BOOL)animated;
- (void)updateTabBarAnimated:(BOOL)animated completion:(id)completion;
- (void)updateTabExposeButtonIndicator;
- (void)updateTabExposeButtonIndicatorExcludingBlankDocuments;
- (id)webView:(id)view createWebViewWithRequest:(id)request;
- (void)webViewClose:(id)close;
- (void)webViewFocus:(id)focus;
@end

@interface BrowserController (Phishing)
- (void)_initializeAntiPhishingService;
- (BOOL)_phoneIsPluggedIn;
- (BOOL)_shouldSetResumeTimer;
- (void)_shutDownAntiPhishingService;
- (void)checkForSyncedDatabase;
- (void)fraudWarningsToggledFromSettings;
- (void)initializeAntiPhishingServiceIfNeeded;
- (BOOL)phoneIsLocked;
- (id)safeBrowsingHostString;
@end

